name: clean-pr
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: pr
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          clean: false
      - name: clean
        run: |
            set -e
            make docker-clean